  version: '3.8'

services:
  app:
    build:
     context: .
    container_name: reservesapi
    restart: unless-stopped
    ports:
      - "443:443"  # HTTPS
    environment:
      - PORT=443
    networks:
      - xarxa_projecte
    volumes:
      - ./models_data:/app/models

networks:
  xarxa_projecte:
    name: xarxa_IOT
    external: true